// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pycdaamffiamrkwdwyur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5Y2RhYW1mZmlhbXJrd2R3eXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjY5NDksImV4cCI6MjA2NzA0Mjk0OX0.38wZr09OElY_zmZ7JGPwjXCOfm4aE6_YVAX7Ar8bKMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});